version: '3.5'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: vtdbuser
      POSTGRES_PASSWORD: vtdbpass
      POSTGRES_DB: vtdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  vtweb:
    depends_on:
      - postgres
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: "node_modules/.bin/node-dev bin/www"
    environment:
      PGUSER: vtdbuser
      PGHOST: postgres
      PGPASSWORD: vtdbpass
      PGDATABASE: vtdb
      COOKIE_SECRET: aboslutelykeyboardcatallday
      AWS_ACCESS_KEY_ID: W58XWCMM67RUNUCTAY9J
      AWS_SECRET_ACCESS_KEY: dydPkNgrXQHfluoLcslygJuKiKH2IrrOoFtCwNqt
